__include__: [
  '../dfine/dfine_hgnetv2_x_coco.yml',
  '../base/rtv4.yml'
]

output_dir: ./outputs/rtv4_hgnetv2_x_coco

teacher_model:
  type: "DINOv3TeacherModel"
  dinov3_repo_path: dinov3/
  dinov3_weights_path: pretrain/dinov3_vitb16_pretrain_lvd1689m.pth
  patch_size: 16
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

HybridEncoder:
  distill_teacher_dim: 768

RTv4Criterion:
  weight_dict:
    loss_distill: 20
  distill_adaptive_params:
    enabled: True
    rho: 2
    delta: 0.25
    default_weight: 20

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epoches: 58

flat_epoch: 29
no_aug_epoch: 8

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: [4, 29, 50]

  collate_fn:
    mixup_epochs: [4, 29]
    stop_epoch: 50