__include__: [
  '../dfine/dfine_hgnetv2_m_coco.yml',
  '../base/rtv4.yml',
  '../dataset/ships_open_vocab.yml'
]

output_dir: ./outputs/rtv4_hgnetv2_m_ships_open_vocab_{date}

checkpoint_freq: 10
plot_freq: 20

epoches: 300

lr_gamma: 0.3
warmup_iter: 4000
flat_epoch: 60
no_aug_epoch: 20

optimizer:
  type: Lion
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00001
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00001
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
  lr: 0.0001
  betas: [0.9, 0.98]
  weight_decay: 0.0002

teacher_model:
  type: "DINOv3TeacherModel"
  dinov3_repo_path: dinov3/
  dinov3_weights_path: pretrain/dinov3_vitb16_pretrain_lvd1689m.pth
  patch_size: 16
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

HybridEncoder:
  distill_teacher_dim: 768

DFINETransformer:
  open_vocab: True
  text_embed_dim: 512
  text_embed_norm: True
  text_logit_scale: 1.0
  learnable_logit_scale: True
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  text_encoder:
    type: CLIPTextEncoder
    model_name: "openai/clip-vit-base-patch32"
    normalize: True
    freeze: True
    cache_text: True
    cache_on_cpu: True

RTv4Criterion:
  weight_dict:
    loss_mal: 1.2
    loss_bbox: 7
    loss_giou: 3
    loss_fgl: 0.2
    loss_ddf: 1.8
    loss_distill: 5
    loss_text: 1.0
  losses: ['mal', 'boxes', 'local', 'text', 'distill']
  distill_adaptive_params:
    enabled: True
    rho: 11
    delta: 1
    default_weight: 5

